---
apiVersion: {{ include "priorityclassversion" . }}
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClassName }}
value: 1000000000
globalDefault: false
description: "This class is used to ensure that istiod has a high priority and is not preempted in favor of other pods."