image:
  repository: eu.gcr.io/gardener-project/gardener/gardener-resource-manager
  tag: latest
  pullPolicy: IfNotPresent

resources: {}

serverBindAddress: 0.0.0.0
serverPort: 10250
metricsPort: 8080
healthPort: 8081

serverCertificate: |
  some-tls-certificate
serverPrivateKey: |
  some-private-key

controllers:
# cacheResyncPeriod: 24h0m0s
  managedResource:
    syncPeriod: 1m0s
    concurrentSyncs: 10
    alwaysUpdate: false
  managedResourceHealth:
    syncPeriod: 1m0s
    concurrentSyncs: 10
  garbageCollector:
    syncPeriod: ""
  tokenInvalidator:
    concurrentSyncs: 0
  tokenRequestor:
    concurrentSyncs: 0
  rootCAController:
    maxConcurrentWorkers: 0
    rootCAPath: "" # path to a file containing the root CA bundle

webhooks:
  projectedTokenMount:
    expirationSeconds: 43200 # 12h

leaderElection:
  enabled: true
  resourceLock: leases
  leaseDuration: 15s
  renewDeadline: 10s
  retryPeriod: 2s

# targetNamespace: ""
# targetKubeconfig: |
#   apiVersion: v1
#   clusters:
#   - cluster:
#       insecure-skip-tls-verify: true
#       server: https://127.0.0.1:6443
#     name: docker-desktop
#   ...
