{{- if and .Values.serverCertificate .Values.serverPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: gardener-resource-manager-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app: gardener
    role: resource-manager
type: kubernetes.io/tls
data:
  tls.crt: {{ b64enc .Values.serverCertificate }}
  tls.key: {{ b64enc .Values.serverPrivateKey }}
{{- end }}
