apiVersion: v1
kind: ServiceAccount
metadata:
  name: blackbox-exporter
  namespace: kube-system
  labels:
    gardener.cloud/role: monitoring
    component: blackbox-exporter
    origin: gardener
automountServiceAccountToken: false
