{{- if .Values.global.vpaEnabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: blackbox-exporter
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: {{ include "deploymentversion" . }}
    kind: Deployment
    name: blackbox-exporter
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledValues: RequestsOnly
{{- end }}
