images:
  machine-controller-manager: image-repository:image-tag
  machine-controller-manager-provider-local: image-repository:image-tag

replicas: 1

podAnnotations: {}
podLabels: {}

providerName: provider-foo

genericTokenKubeconfigSecretName: generic-token-kubeconfig

namespace:
  uid: uuid-of-namespace

metricsPort: 10258
metricsPortLocal: 10259

vpa:
  enabled: true
  updatePolicy:
    updateMode: "Auto"
